### ISSUE TITLE
Realtime usage

### ISSUE THREAD

**Issue by fire** [Sindhu-Hegde/pseudo-visual-speech-denoising#4]
Is the network able to process audio for interactive use?

**Comment by Sindhu-Hegde** [comment]
We do not have any interactive demo yet! You can try running the inference.py file to get the results.

**Comment by fire** [comment]
I've having trouble running inference.py.

**Comment by Sindhu-Hegde** [comment]
Can you elaborate what is the exact issue?

**Comment by fire** [comment]
```
> pip install -r requirements.txt
Requirement already satisfied: librosa==0.7.0 in ...\lib\site-packages (from -r requirements.txt (line 1)) (0.7.0)
ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (from -r requirements.txt (line 2)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1)
ERROR: No matching distribution found for torch==1.6.0 (from -r requirements.txt (line 2))
```

**Comment by Sindhu-Hegde** [comment]
What Python version are you using? Ensure that you are using 64-bit Python with the version that is mentioned in ReadMe file (`Python 3.7+`)

**Comment by fire** [comment]
```
>python --version
Python 3.8.5
```

**Comment by Sindhu-Hegde** [comment]
We have tested the code with `Python 3.7.4` and it works fine. Probably torch version 1.16.0 isn't compatible with Python 3.8+. 
Kindly install `Python 3.7.4`.

**Comment by fire** [comment]
Ah. Thanks I'll wait for an update.
