### ISSUE TITLE
Real-time

### ISSUE THREAD

**Issue by msaad1311** [Sindhu-Hegde/pseudo-visual-speech-denoising#5]
Hey. I went through the paper the results and I must mention that the work is remarkable. Congrats achieving such a tremendous results. However, I was wondering whether the model can be used in real-time applications or not? if it can, can you suggest the ways to do it?

**Comment by Sindhu-Hegde** [comment]
Glad that you liked it, thanks for your interest. The technique is fast, but probably can be improved for memory efficiency. We haven't tested it on any real-time applications though!

**Comment by msaad1311** [comment]
Thanks for your response. Indeed I did try on different audio sounds and it is fast but I am still wondering whether we can use in real-time application such as noise cancellation during calls. Can you suggest something that we can do to cater this?

**Comment by prajwalkr** [comment]
You can do a bit of hyper-parameter tuning and see if a model with fewer layers can give approx. the same scores. You can try other efficient architecture types that are recently proposed.

**Comment by msaad1311** [comment]
Thanks a lot for your responses. I have one more question and I am really sorry for that. But when I try your architecture on different sounds, for example using baby crying sound, the model is unable to perform well. Can you suggest something that I may change to cater such noises?

**Comment by Sindhu-Hegde** [comment]
Hi, our architecture performs pretty well on all kinds of noises, except for the human noise. If the human voice is considered as noise, then that is a separate problem, popularly known as "Speaker Separation". There are a few works in this space, you can have a look at them if interested:
[1] [The Conversation: Deep Audio-Visual Speech Enhancement](https://www.robots.ox.ac.uk/~vgg/demo/theconversation/)
[2] [Looking to Listen at the Cocktail Party: A Speaker-Independent Audio-Visual Model for Speech Separation](https://looking-to-listen.github.io/)

**Comment by msaad1311** [comment]
Sorry for late reply. Thanks a lot. I got it. I will try to avoid using using human voices then :).

Once again thanks a lot for your support.
