### ISSUE TITLE
Could you tell me what would be the function of tmp.wav in the inference.py code...thank you

### ISSUE THREAD

**Issue by SGT103** [Sindhu-Hegde/pseudo-visual-speech-denoising#6]

**Comment by Sindhu-Hegde** [comment]
The "tmp.wav" file (line: https://github.com/Sindhu-Hegde/pseudo-visual-speech-denoising/blob/main/inference.py#L17) extracts the audio from the input noisy (audio/video) file. This is to ensure the wav file is extracted from any other input format (example mp4).
