### ISSUE TITLE
broken links of Denoising and Lipsync-Student model weights 

### ISSUE THREAD

**Issue by ZhengRachel** [Sindhu-Hegde/pseudo-visual-speech-denoising#9]
Hi, the links of Denoising and Lipsync-Student model weights are broken again.  Would you mind updating them?  Thanks!!!

**Comment by awarebayes** [comment]
Same issue

**Comment by Tejaswini167** [comment]
Hi, did anyone find the links for the weights? Would be greatly helpful....Thanks.

**Comment by Sindhu-Hegde** [comment]
The links have now been updated.
